### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by rcoletti116** [SimonGolms/homekit-qrcode#1]
Cool project! Just curious if this creates working HomeKit QR codes. I’ve tried using it and can generate a QR, but it doesn’t work to add a device in HomeKit.

From what I’ve read elsewhere HomeKit expects a payload based on some other properties behind the 8 digit code. I’m curious to hear your thoughts and use-cases.

**Comment by SimonGolms** [comment]
Hi @rcoletti116, is it possible that you forgot to provide the `setupId`?
Anyway, I just released a new version with updated packages and improved documentation. I hope I could answer your question in the [FAQs](https://github.com/SimonGolms/homekit-qrcode#faq) section?

**Comment by rcoletti116** [comment]
I think this must be it. I thought the issue was setupId but I didn't see a way to input it previously. Thanks for the updates.
